const baseTasks = [
    {
        id: 0,
        projectId: 0,
        members: [0, 2, 4, 5, 6],
        title: "Google Auth",
        description: "Implement Google Auth (G-Auth) into authentication workflow.",
        from: new Date(2025, 9, 28, 9, 15),
        to: new Date(2025, 10, 7, 16, 40),
        todos: [
            {id: 0, title: "Integrate G-Auth API", checked: false},
            {id: 1, title: "Test with sandbox credentials", checked: false},
        ],
    },
    {
        id: 1,
        projectId: 1,
        members: [2, 3, 4, 6],
        title: "Main Dashboard",
        description: "Produce mock-up and prototype for the new staff dashboard.",
        from: new Date(2025, 9, 31, 10, 25),
        to: new Date(2025, 10, 8, 14, 10),
        todos: [
            {id: 0, title: "Wireframe layouts", checked: false},
            {id: 1, title: "Client review and feedback", checked: false},
        ],
    },
    {
        id: 2,
        projectId: 0,
        members: [0, 2, 4, 5, 6],
        title: "API Keys",
        description: "Refresh API Keys in line with information management policy.",
        from: new Date(2025, 10, 2, 9, 45),
        to: new Date(2025, 10, 11, 16, 10),
        todos: [
            {id: 0, title: "Rotate production keys", checked: false},
            {id: 1, title: "Document expiry dates", checked: false},
        ],
    },
    {
        id: 3,
        projectId: 1,
        members: [2, 3, 4, 6],
        title: "Update DSAR",
        description: "Compile and report Data Subject Access Request information for company accounts.",
        from: new Date(2025, 10, 5, 9, 25),
        to: new Date(2025, 10, 11, 14, 55),
        todos: [
            {id: 0, title: "Collate recent DSARs", checked: false},
            {id: 1, title: "Submit summary to HR", checked: false},
        ],
    },
    {
        id: 4,
        projectId: 0,
        members: [0, 2, 4, 5, 6],
        title: "Lunch vouchers",
        description: "Order lunch voucher codes from HR office for December.",
        from: new Date(2025, 10, 4, 9, 5),
        to: new Date(2025, 10, 9, 17, 0),
        todos: [
            {id: 0, title: "Confirm eligible staff", checked: false},
            {id: 1, title: "Send order to HR", checked: false},
        ],
    },
    {
        id: 5,
        projectId: 1,
        members: [2, 3, 6],
        title: "Quarterly KPI Dashboard",
        description: "Develop Q4 KPI dashboard with real-time data tracking.",
        from: new Date(2025, 10, 8, 9, 20),
        to: new Date(2025, 10, 18, 15, 45),
        todos: [
            {id: 0, title: "Build data queries", checked: false},
            {id: 1, title: "Design KPI widgets", checked: false},
        ],
    },
    {
        id: 6,
        projectId: 0,
        members: [0, 2, 5, 6],
        title: "System Maintenance Rollout",
        description: "Deploy latest patch updates across all dev servers.",
        from: new Date(2025, 10, 10, 10, 35),
        to: new Date(2025, 10, 13, 16, 5),
        todos: [
            {id: 0, title: "Patch server cluster A", checked: false},
            {id: 1, title: "Validate uptime logs", checked: false},
        ],
    },
    {
        id: 7,
        projectId: 2,
        members: [1, 3, 7],
        title: "Staff Briefing Document",
        description: "Prepare briefing document for December all-hands meeting.",
        from: new Date(2025, 10, 12, 9, 10),
        to: new Date(2025, 10, 16, 15, 20),
        todos: [
            {id: 0, title: "Gather department updates", checked: false},
            {id: 1, title: "Proofread and submit draft", checked: false},
        ],
    },
    {
        id: 8,
        projectId: 1,
        members: [3, 4, 6],
        title: "Customer Data Migration",
        description: "Migrate customer data from legacy CRM to new platform.",
        from: new Date(2025, 10, 13, 10, 25),
        to: new Date(2025, 10, 22, 14, 50),
        todos: [
            {id: 0, title: "Validate CSV imports", checked: false},
            {id: 1, title: "Run migration scripts", checked: false},
        ],
    },
    {
        id: 9,
        projectId: 0,
        members: [0, 2, 4, 5],
        title: "Security Audit Preparation",
        description: "Prepare evidence and documentation for annual IT security audit.",
        from: new Date(2025, 10, 15, 9, 50),
        to: new Date(2025, 10, 21, 16, 25),
        todos: [
            {id: 0, title: "Check compliance checklist", checked: false},
            {id: 1, title: "Submit internal audit log", checked: false},
        ],
    },
    {
        id: 10,
        projectId: 1,
        members: [2, 3, 6],
        title: "Expense Portal Year-End Report",
        description: "Compile and export expense summaries for finance reconciliation.",
        from: new Date(2025, 10, 18, 9, 15),
        to: new Date(2025, 10, 25, 14, 0),
        todos: [
            {id: 0, title: "Review Q4 claims", checked: false},
            {id: 1, title: "Submit totals to finance", checked: false},
        ],
    },
    {
        id: 11,
        projectId: 2,
        members: [0, 1, 3, 7],
        title: "Holiday Rota Planning",
        description: "Coordinate staff holiday rota for Christmas period.",
        from: new Date(2025, 10, 20, 9, 30),
        to: new Date(2025, 10, 27, 16, 10),
        todos: [
            {id: 0, title: "Confirm team availability", checked: false},
            {id: 1, title: "Publish rota on MakeIToday", checked: false},
        ],
    },
    {
        id: 12,
        projectId: 0,
        members: [0, 2, 5, 6],
        title: "Office Equipment Audit",
        description: "Check all IT and AV equipment for maintenance needs.",
        from: new Date(2025, 10, 22, 10, 0),
        to: new Date(2025, 10, 29, 15, 30),
        todos: [
            {id: 0, title: "Inspect meeting rooms", checked: false},
            {id: 1, title: "Record damaged kit", checked: false},
        ],
    },
    {
        id: 13,
        projectId: 1,
        members: [2, 3, 4],
        title: "End-of-Year Survey",
        description: "Create and distribute staff satisfaction survey for 2025.",
        from: new Date(2025, 10, 24, 9, 25),
        to: new Date(2025, 11, 2, 15, 40),
        todos: [
            {id: 0, title: "Draft survey questions", checked: false},
            {id: 1, title: "Send via MakeIToday", checked: false},
        ],
    },
    {
        id: 14,
        projectId: 2,
        members: [0, 1, 3, 7],
        title: "Staff Recognition Programme",
        description: "Finalise nominations for annual staff awards ceremony.",
        from: new Date(2025, 10, 26, 10, 15),
        to: new Date(2025, 11, 3, 16, 5),
        todos: [
            {id: 0, title: "Compile nominations list", checked: false},
            {id: 1, title: "Confirm award categories", checked: false},
        ],
    },
    {
        id: 15,
        projectId: 0,
        members: [0, 2, 4, 5],
        title: "System Backup Validation",
        description: "Validate automated nightly backups for December rollouts.",
        from: new Date(2025, 10, 28, 9, 10),
        to: new Date(2025, 11, 5, 15, 25),
        todos: [
            {id: 0, title: "Check integrity of archives", checked: false},
            {id: 1, title: "Log results for weekly review", checked: false},
        ],
    },
    {
        id: 16,
        projectId: 1,
        members: [2, 3, 6],
        title: "Christmas Campaign Analytics",
        description: "Collect and analyse engagement data from Christmas marketing campaigns.",
        from: new Date(2025, 10, 29, 9, 30),
        to: new Date(2025, 11, 10, 16, 10),
        todos: [
            {id: 0, title: "Gather email campaign stats", checked: false},
            {id: 1, title: "Prepare presentation slides", checked: false},
        ],
    },
    {
        id: 17,
        projectId: 2,
        members: [1, 3, 7],
        title: "Payroll Reconciliation",
        description: "Reconcile November and December payroll records.",
        from: new Date(2025, 10, 30, 10, 0),
        to: new Date(2025, 11, 8, 14, 30),
        todos: [
            {id: 0, title: "Check hourly staff data", checked: false},
            {id: 1, title: "Submit report to finance", checked: false},
        ],
    },
    {
        id: 18,
        projectId: 0,
        members: [0, 2, 5, 6],
        title: "Network Infrastructure Review",
        description: "Evaluate current network performance ahead of winter upgrades.",
        from: new Date(2025, 11, 1, 9, 20),
        to: new Date(2025, 11, 6, 15, 40),
        todos: [
            {id: 0, title: "Run latency tests", checked: false},
            {id: 1, title: "Prepare summary document", checked: false},
        ],
    },
    {
        id: 19,
        projectId: 1,
        members: [2, 3, 4],
        title: "Client Portfolio Update",
        description: "Update CRM records with latest client engagement details.",
        from: new Date(2025, 11, 2, 10, 15),
        to: new Date(2025, 11, 7, 16, 0),
        todos: [
            {id: 0, title: "Verify client data accuracy", checked: false},
            {id: 1, title: "Upload attachments to CRM", checked: false},
        ],
    },
    {
        id: 20,
        projectId: 2,
        members: [0, 1, 3, 7],
        title: "Christmas Newsletter",
        description: "Design and publish festive newsletter on MakeIToday.",
        from: new Date(2025, 11, 3, 9, 35),
        to: new Date(2025, 11, 10, 14, 55),
        todos: [
            {id: 0, title: "Draft copy for newsletter", checked: false},
            {id: 1, title: "Add festive visuals", checked: false},
        ],
    },
    {
        id: 21,
        projectId: 0,
        members: [0, 2, 4, 5, 6],
        title: "Printer Replacement Rollout",
        description: "Replace ageing printers across admin floors before year-end.",
        from: new Date(2025, 11, 5, 9, 25),
        to: new Date(2025, 11, 12, 15, 35),
        todos: [
            {id: 0, title: "Confirm replacement models", checked: false},
            {id: 1, title: "Book IT support assistance", checked: false},
        ],
    },
    {
        id: 22,
        projectId: 1,
        members: [2, 3, 4, 6],
        title: "End-of-Year Budget Review",
        description: "Prepare financial summary for board meeting.",
        from: new Date(2025, 11, 6, 9, 45),
        to: new Date(2025, 11, 14, 16, 15),
        todos: [
            {id: 0, title: "Collect Q4 expenditure data", checked: false},
            {id: 1, title: "Prepare board summary", checked: false},
        ],
    },
    {
        id: 23,
        projectId: 2,
        members: [0, 1, 3, 7],
        title: "IT Policy Update",
        description: "Revise company IT policy to reflect new data retention guidelines.",
        from: new Date(2025, 11, 7, 10, 30),
        to: new Date(2025, 11, 12, 14, 50),
        todos: [
            {id: 0, title: "Draft revised sections", checked: false},
            {id: 1, title: "Obtain legal review", checked: false},
        ],
    },
    {
        id: 24,
        projectId: 0,
        members: [0, 2, 5, 6],
        title: "Helpdesk Workflow Improvements",
        description: "Optimise staff ticket triage process in MakeIToday.",
        from: new Date(2025, 11, 10, 9, 15),
        to: new Date(2025, 11, 18, 15, 5),
        todos: [
            {id: 0, title: "Review response categories", checked: false},
            {id: 1, title: "Trial auto-assignment rules", checked: false},
        ],
    },
    {
        id: 25,
        projectId: 1,
        members: [2, 3, 4],
        title: "December Campaign Debrief",
        description: "Analyse December social media and advert performance.",
        from: new Date(2025, 11, 11, 9, 50),
        to: new Date(2025, 11, 20, 14, 25),
        todos: [
            {id: 0, title: "Pull performance metrics", checked: false},
            {id: 1, title: "Prepare insights summary", checked: false},
        ],
    },
    {
        id: 26,
        projectId: 2,
        members: [1, 3, 7],
        title: "Christmas Office Setup",
        description: "Arrange decorations and staff common room setup.",
        from: new Date(2025, 11, 12, 9, 20),
        to: new Date(2025, 11, 15, 15, 50),
        todos: [
            {id: 0, title: "Book storage room access", checked: false},
            {id: 1, title: "Order lights and ornaments", checked: false},
        ],
    },
    {
        id: 27,
        projectId: 0,
        members: [0, 2, 4, 5],
        title: "Year-End Archiving",
        description: "Archive inactive projects and clean shared drives.",
        from: new Date(2025, 11, 13, 9, 35),
        to: new Date(2025, 11, 23, 16, 0),
        todos: [
            {id: 0, title: "Move files to archive", checked: false},
            {id: 1, title: "Confirm completion with manager", checked: false},
        ],
    },
    {
        id: 28,
        projectId: 1,
        members: [2, 3, 6],
        title: "January Kick-Off Planning",
        description: "Draft materials and slides for January 2026 project launches.",
        from: new Date(2025, 11, 16, 9, 45),
        to: new Date(2025, 11, 23, 15, 15),
        todos: [
            {id: 0, title: "Confirm agenda topics", checked: false},
            {id: 1, title: "Collect department updates", checked: false},
        ],
    },
    {
        id: 29,
        projectId: 2,
        members: [0, 1, 3, 7],
        title: "Winter IT Maintenance Window",
        description: "Perform December maintenance on production systems.",
        from: new Date(2025, 11, 18, 9, 25),
        to: new Date(2025, 11, 27, 15, 55),
        todos: [
            {id: 0, title: "Back up critical data", checked: false},
            {id: 1, title: "Deploy system patches", checked: false},
        ],
    }
];

export default baseTasks;
